---
title: "鄉村都市地區車站人數比較"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
   self_contained: false
   number_sections: false
   css: style.css
#  rmdformats::html_clean:
#    self_contained: false
#    highlight: kate
#    use_bookdown: true
#    number_sections: false
#    css: style.css
---


```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(svglite)
## Global options
options(max.print="75")
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	comment = NA,
	dev = 'svglite',
	out.width = '100%',
	fig.dim=c(8,4)
)
```


```{r}
ori_dir <- getwd()
setwd('..')
source('clean_explore.R')
setwd(ori_dir)
library(gridExtra)
```


```{r}
tmp <- data %>% 
  filter(date == ymd('2016-05-25')) %>% 
  filter(num_in > 0 & num_out > 0) %>%
  filter(num_in + num_out >= 10) %>%
  arrange(desc(num_in + num_out))

top_4_big_stations <- c('台北', '桃園', '台南', '台中', '新竹', '高雄')
top_4_small_stations <- tmp$station[130:135]
```

```{r}
years <- c(2010)
stations <- c(top_4_big_stations, top_4_small_stations)
DT::datatable(filter_sta_y(data, stations, years))
```


```{r}
plot_lst = list()
years <- c(2010, 2012, 2014)
for (i in 1:3) {
  stations <- c(top_4_big_stations[1:2], top_4_small_stations[1:2])
  for (year in years) {
    filtered_data <- filter_sta_y(data, stations, year)
    
    #plot_lst[[i]] <- plot_daily(filtered_data, print = FALSE)
    plot_daily(filtered_data, print = TRUE)
  }
  
  top_4_big_stations <- top_4_big_stations[-(1:2)]
  top_4_small_stations <- top_4_small_stations[-(1:2)]
}
```


```{r}
#for (i in 1:3) print(plot_lst[[i]])
#do.call(grid.arrange, args = plot_lst)
```

